recipiebook/recipiebook/urls.py
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.urls import include, re_path, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('recipies/', include("recipies.urls")),
    re_path(r'^.*$', RedirectView.as_view(url='/recipies/', permanent=False)),
]

recipiebook/recipies/urls.py
from django.urls import path
import recipies.views.recipie

urlpatterns = [
        path("", recipies.views.recipie.RecipieView.as_view()),
        path("<recipieid>/", recipies.views.recipie.RecipieView.as_view(),
             name="recipie"),
        ]

recipiebook/recipies/models/item.py
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=100)
    itemlist = models.ForeignKey('Itemlist', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

recipiebook/recipies/models/itemlist.py
from django.db import models


class Itemlist(models.Model):
    name = models.CharField(max_length=100)
    recipie = models.ForeignKey('Recipie', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

recipiebook/recipies/models/recipie.py
from django.db import models


class Recipie(models.Model):
    name = models.CharField(max_length=1000)
    amount = models.PositiveSmallIntegerField(blank=True, null=True,
                                              verbose_name="Personen")

    def __str__(self):
        return self.name

recipiebook/recipies/models/shoppingitem.py
from django.db import models


class Shoppingitem(models.Model):
    name = models.CharField(max_length=100)
    recipie = models.ForeignKey('Recipie', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

recipiebook/recipies/views/recipie.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from recipies.models.recipie import Recipie


class RecipieView(TemplateView):
    template_name = "recipies/recipie.html"

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        context['recipies'] = Recipie.objects.all()
        if "recipieid" in kwargs:
            context['recipie'] = get_object_or_404(Recipie,
                                                   pk=kwargs['recipieid'])
        return context

recipiebook/recipies/templates/recipies/recipie.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>RecipieBook</title>
	<link rel="stylesheet" href="{% static 'recipies/normal.css' %}">
	<link rel="stylesheet" href="{% static 'recipies/style.css' %' %}">
</head>
<body>
	<h1>Rezepte</h1>
	<div class="nav">
		<ul>
			{% for recipieitem in recipies %}
			<li><a href='{% url 'recipie' recipieitem.id %}'>{{ recipieitem.name }}</a></li>
			{% endfor %}
		</ul>
	</div>
	{% if recipie %}
	<div class="wrapper">
		<h2>{{recipie.name}}</h2>
		<div class="left">
			{% if recipie.amount %}
				Für {{ recipie.amount }} Personen
			{% endif %}
			{% for itemlist in recipie.itemlist_set.all %}
			<h3>{{ itemlist.name }}</h3>
			<ul>
				{% for item in itemlist.item_set.all %}
				<li>{{ item.name }}</li>
				{% endfor %}
			</ul>
			{% endfor %}
			</div>
			<div class="right boxed">
				<h3>Einkaufszeddele</h3>
				<ul>
					{% for item in recipie.shoppingitem_set.all %}
					<li>{{ item.name }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
	{% endif %}
</body>
</html>